# ~/.config/yappers-of-linux/config.toml

# Add "urgent" for persistent notifications (ignores DND)
notifications = "start,pause,stop" # Examples: "start,pause,stop" | "urgent" | "false"
model = "tiny" # tiny/base/small/medium/large
device = "cpu" # cpu/cuda
language = "en"
fast_mode = false
enable_typing = true
