# ~/.config/yappers-of-linux/config.toml

notifications = "start,pause,stop" # Examples: "start,pause,stop" | "urgent" | "false"
model = "tiny" # tiny/base/small/medium/large
device = "cpu" # cpu/gpu
language = "" # "auto"/"" for auto-detect
fast_mode = false
enable_typing = true
output_file = false # ~/.config/yappers-of-linux/output.txt

# For more help run `yap help config`